source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.7.5'

gem 'discordrb'
gem 'dotenv'
gem 'activesupport'
gem 'pry'
gem 'wit'
gem 'httparty'
gem 'google-apis-adsense_v1_4', '~> 0.1'
gem 'google-apis-analytics_v3', '~> 0.1'
gem 'google-apis-bigquery_v2', '~> 0.1'
gem 'google-apis-calendar_v3', '~> 0.1'
gem 'google-apis-drive_v3', '~> 0.1'
gem 'google-apis-gmail_v1', '~> 0.1'
gem 'google-apis-pubsub_v1', '~> 0.1'
gem 'google-apis-sheets_v4', '~> 0.1'
gem 'google-apis-translate_v2', '~> 0.1'
gem 'google-apis-vision_v1', '~> 0.1'
gem 'google-apis-youtube_v3', '~> 0.1'

gem 'thor', '~> 1.0'
gem 'os', '~> 0.9'
gem 'rmail', '~> 1.1'
gem 'dotenv'
